In [1]:
import numpy as np

In [2]:
a = []
for i in range(100):
    a.append(i)

In [4]:
print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [5]:
type(a)

list

In [15]:
aa = np.array([[1,2,3,4,5], [2,3,4,5,6]])

In [16]:
type(aa)

numpy.ndarray

In [17]:
aa.shape

(2, 5)

In [19]:
b = np.array([[1], [2], [3], [4], [5]])

In [20]:
b.shape

(5, 1)

In [30]:
aa = np.array([[1,2,3,4,5]])

In [31]:
aa.shape

(1, 5)

In [23]:
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [26]:
a = np.array(a)

In [27]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [28]:
type(a)

numpy.ndarray

In [29]:
aa

array([1, 2, 3, 4, 5])

In [36]:
a = [[1,2,3,4,5], [2,3,4,5,6]]

In [37]:
a

[[1, 2, 3, 4, 5], [2, 3, 4, 5, 6]]

In [38]:
len(a)

2

In [39]:
a[1]

[2, 3, 4, 5, 6]

In [44]:
a = [1,2,'3',4,"hello", print, range]

In [46]:
print(a)

[1, 2, '3', 4, 'hello', <built-in function print>, <class 'range'>]


In [45]:
print(np.array(a))

[1 2 '3' 4 'hello' <built-in function print> <class 'range'>]


In [52]:
c = np.full((3,2), 5)

In [49]:
c

array([[5, 5],
       [5, 5],
       [5, 5]])

In [61]:
d = np.eye(4, dtype=int)

In [75]:
print(d, type(d))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] <class 'numpy.ndarray'>


In [66]:
random_int = np.random.random((5,6))

In [74]:
random_int

array([[0.0350522 , 0.6828361 , 0.62111035, 0.49521466, 0.41186559,
        0.09533693],
       [0.0682683 , 0.94185866, 0.53756719, 0.31336842, 0.14877274,
        0.27485628],
       [0.66689365, 0.51666789, 0.8200815 , 0.51639531, 0.34996437,
        0.20040056],
       [0.43759962, 0.64167495, 0.33655467, 0.15220557, 0.73743474,
        0.62473362],
       [0.75527182, 0.17163874, 0.41619092, 0.66324688, 0.10062574,
        0.58143658]])

In [71]:
random_int[:1, 3:]

array([[0.49521466, 0.41186559, 0.09533693]])

In [73]:
random_int[-1]

array([0.75527182, 0.17163874, 0.41619092, 0.66324688, 0.10062574,
       0.58143658])

In [79]:
d = np.zeros((10, 8))

In [80]:
d

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [84]:
X = np.array([[1,2], [3,4]])
Y = np.array([[5,6], [7,8]])

In [85]:
X.shape, Y.shape

((2, 2), (2, 2))

In [87]:
print(X+Y, np.add(X, Y))

[[ 6  8]
 [10 12]] [[ 6  8]
 [10 12]]


In [88]:
print(X-Y, np.subtract(X, Y))

[[-4 -4]
 [-4 -4]] [[-4 -4]
 [-4 -4]]


In [89]:
print(X*Y, np.multiply(X, Y))

[[ 5 12]
 [21 32]] [[ 5 12]
 [21 32]]


In [91]:
np.matmul(X, Y)

array([[19, 22],
       [43, 50]])

In [92]:
print(X/Y, np.divide(X, Y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]] [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [94]:
print(np.sqrt(Y))

[[2.23606798 2.44948974]
 [2.64575131 2.82842712]]


In [95]:
print(X.dot(Y), np.dot(X, Y))

[[19 22]
 [43 50]] [[19 22]
 [43 50]]


In [96]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [97]:
a.dot(b)

55

In [98]:
sum(a)

15

In [99]:
np.sum(a)

15

In [107]:
print(np.sum(Y, axis = 1))

[11 15]


In [108]:
X = np.array([[1,2,3], [3,4,5]])

In [109]:
X.shape

(2, 3)

In [115]:
summer = 0
for i in range(X.shape[0]):
    for j in range(X.shape[1]):
        summer+=X[i][j]

In [116]:
summer

18

In [117]:
summer = 0
col = 1
for i in range(X.shape[0]):
    summer+=X[i][col]
print(summer)

6


In [118]:
summer = 0
row = 1
for i in range(X.shape[1]):
    summer+=X[row][i]
print(summer)

12


In [119]:
for i in range(2):
    for j in range(3):
        print(i, "I", j, "J")

0 I 0 J
0 I 1 J
0 I 2 J
1 I 0 J
1 I 1 J
1 I 2 J


In [121]:
a = np.array([1,2,3,4,5])
b = np.array([1,2,3,4,5])

In [122]:
b = b**2

In [123]:
b

array([ 1,  4,  9, 16, 25])

In [128]:
print(np.stack((a, b), axis = 1), np.stack((a, b), axis = 1).shape)

[[ 1  1]
 [ 2  4]
 [ 3  9]
 [ 4 16]
 [ 5 25]] (5, 2)


In [130]:
print(np.stack((a, b), axis = 0), np.stack((a, b), axis = 0).shape)

[[ 1  2  3  4  5]
 [ 1  4  9 16 25]] (2, 5)


In [131]:
a = np.stack((a, b), axis = 0)

In [132]:
a

array([[ 1,  2,  3,  4,  5],
       [ 1,  4,  9, 16, 25]])

In [146]:
print(a.reshape((-1, 5)))

[[ 1  2  3  4  5]
 [ 1  4  9 16 25]]


In [148]:
print(a.ravel())

[ 1  2  3  4  5  1  4  9 16 25]


In [166]:
a = np.arange(10) + 5

In [167]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [171]:
np.random.shuffle(a)

In [172]:
a

array([ 8,  5,  7, 13,  9, 11, 12, 10,  6, 14])

In [174]:
random = np.random.rand(2,3)

In [175]:
random

array([[0.70282563, 0.31363512, 0.7109355 ],
       [0.54899393, 0.07380699, 0.65418841]])

In [179]:
random = np.random.randn(2,3)

In [180]:
random

array([[ 2.20574307,  1.11953998,  0.01879304],
       [-0.34175688,  1.74368766,  0.69561961]])

In [192]:
a = np.random.randint(0, 10, 100)

In [193]:
a

array([4, 1, 2, 6, 3, 6, 1, 7, 3, 4, 5, 6, 1, 8, 5, 3, 0, 5, 0, 2, 2, 2,
       2, 2, 3, 5, 7, 8, 3, 1, 1, 2, 0, 0, 3, 7, 8, 9, 3, 4, 0, 7, 2, 5,
       0, 9, 4, 2, 5, 3, 9, 9, 8, 3, 2, 9, 1, 8, 9, 8, 4, 8, 9, 7, 4, 8,
       2, 6, 5, 3, 7, 4, 3, 5, 0, 9, 1, 3, 2, 1, 3, 7, 6, 0, 5, 3, 7, 9,
       1, 9, 1, 7, 8, 3, 1, 0, 4, 8, 8, 5])

In [198]:
choice = np.random.choice(a)

In [199]:
choice

2

In [200]:
for i in range(10):
    choice = np.random.choice(a)
    print(choice)

7
7
5
8
9
9
8
0
8
8
